[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "video_processing"
version = "0.0.1"
dependencies = [
  "numpy"
]

[tool.hatch.build.targets.wheel]
packages = ["."]
