[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ops"
version = "0.0.1"
dependencies = [
  "Pillow"
]

[tool.hatch.build.targets.wheel]
packages = [".", "src/ops"]
